#!/bin/sh

# ----------------------------------------------------------------------------
# Maven on docker scripts
#
# Tools that need to be available:
# ------------------
#   docker - must be accessible from command line
#
# Optional ENV vars
# -----------------
#   LOCAL_RESPOSITORY - location of maven local repository
#   MAVEN_OPTS - parameters passed to the Java VM when running Maven
#     e.g. to debug Maven itself, use
#       set MAVEN_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000
# ----------------------------------------------------------------------------


# resolve local repository
if [ -z "$LOCAL_RESPOSITORY" ] ; then
  LOCAL_RESPOSITORY="$HOME/.m2"
else
  # make it fully qualified
  LOCAL_RESPOSITORY=$(cd "$LOCAL_RESPOSITORY" && pwd)
fi

# echo "Using m2 repo at $LOCAL_RESPOSITORY"


docker run -it \
    -v "${LOCAL_RESPOSITORY}:/root/.m2" \
    -v "$(pwd):/sources" \
    -v /var/run/docker.sock:/run/docker.sock \
    -w /sources \
    -e "USER=${USER}" \
    -e "MAVEN_OPTS=${MAVEN_OPTS}" \
    maven \
    mvn $@
